# Generated by Django 4.1.1 on 2022-10-05 01:30

import ckeditor.fields
from django.db import migrations, models
import pstcall.models


class Migration(migrations.Migration):

    dependencies = [
        ('pstcall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=80)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=pstcall.models.ruta)),
            ],
        ),
        migrations.RenameField(
            model_name='instructivo',
            old_name='titulo',
            new_name='vehiculo',
        ),
    ]
