# Generated by Django 4.1.1 on 2022-10-06 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pstcall', '0002_novedad_rename_titulo_instructivo_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercio', models.CharField(max_length=60)),
                ('cuit', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('localidad', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=60)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
