# Generated by Django 4.1.1 on 2022-10-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pstcall", "0005_remove_novedad_fecha_alter_novedad_cuerpo"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructivo",
            name="link",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
    ]
