# Generated by Django 4.1.1 on 2022-10-16 01:08

from django.db import migrations, models
import pstcall.models


class Migration(migrations.Migration):

    dependencies = [
        ("pstcall", "0006_instructivo_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructivo",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to=pstcall.models.ruta
            ),
        ),
        migrations.AlterField(
            model_name="instructivo",
            name="link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
