# Generated by Django 4.1.1 on 2022-10-23 17:53

from django.db import migrations, models
import pstcall.models


class Migration(migrations.Migration):

    dependencies = [
        ("pstcall", "0007_alter_instructivo_archivo_alter_instructivo_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria_manual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=150)),
                ("link", models.CharField(max_length=150)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to=pstcall.models.ruta
                    ),
                ),
            ],
        ),
    ]
