# Generated by Django 4.1.1 on 2022-10-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pstcall", "0008_categoria_manual_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructivo",
            name="hits",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manual",
            name="hits",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
